"""Apply the verified corrections to the SEGAN manuscript.

Every replacement is an exact literal pair; the script prints a per-item count so
that a silent no-op is impossible.
"""
from __future__ import annotations

import pathlib
import sys

P = pathlib.Path("SEGAN_manuscript_revised_2026-09-13.md")
s = P.read_text(encoding="utf-8")
orig = s

R: list[tuple[str, str]] = []


def rep(old: str, new: str) -> None:
    R.append((old, new))


# ---------------------------------------------------------------- terminology
rep("the admissibility check that decides whether an action is legal",
    "the admissibility screen that decides whether an action is legal")
rep("The literature accordingly records gains without identifying their source "
    "[see Section 2 for the formal decomposition].",
    "The literature accordingly records gains without identifying their source "
    "(Section 3 supplies the decomposition).")
rep("**Challenge 1 -- exact optimality is combinatorial.**",
    "**Challenge 1: exact optimality is combinatorial.**")
rep("**Challenge 2 -- value and accessibility are different questions.**",
    "**Challenge 2: value and accessibility are different questions.**")
rep("**Challenge 3 -- the value may be an artefact of the evaluator's convention.**",
    "**Challenge 3: the value may be an artefact of the evaluator's convention.**")
rep("**A condition is declared weakly identifiable, and excluded from the primary test family, when",
    "**A condition is declared non-identifiable, and excluded from the primary test family, when")
rep("Both groups are therefore weakly identifiable by the criterion of Section 2.6.",
    "Both groups are therefore non-identifiable by the criterion of Section 2.6.")
rep("**The instance rule changes the picture, and the correction is part of the result.**",
    "**The instance rule changes the picture, and the correction is part of the result.**")
rep("$\\Gamma_{\\mathrm{LA}}$ is the amount of cumulative recovery that a one-step rule forfeits",
    "$\\Gamma_{\\mathrm{LA}}$ is the amount of cumulative recovery that a one-step exact rule forfeits")
rep("the cause is the action set rather than the capacity parameters. Neither capacity parameter "
    "repairs the degeneracy anywhere in the operating range.",
    "the cause is the action set rather than the capacity-rule parameters. Neither capacity-rule "
    "parameter repairs the degeneracy anywhere in the operating range.")
rep("the rolling depth-2 controller is not guaranteed to beat the one-step rule and empirically does not",
    "the rolling depth-2 controller is not guaranteed to beat the one-step exact rule and empirically "
    "does not")

# ------------------------------------------------- sentence-connective em dashes
rep("a committed plan needs five steps of foresight to capture the gap -- and without a budget "
    "captures only 21% of it even at depth four -- while a rolling depth-2 controller captures "
    "99.4--99.8% and depth 3 captures it exactly, matching the offline optimum.",
    "a committed plan needs five steps of foresight to capture the gap, and without a budget captures "
    "only 21% of it even at depth four, while a rolling depth-2 controller captures 99.4--99.8% and "
    "depth 3 captures it exactly, matching the offline optimum.")
rep("a heuristic claimed to be near-optimal and a thousand times faster [12] -- which weakens",
    "a heuristic claimed to be near-optimal and a thousand times faster [12], which weakens")
rep("the premise of that competition -- that the benchmark contains benefit that *some* policy "
    "could capture -- is never checked",
    "the premise of that competition, namely that the benchmark contains benefit that *some* policy "
    "could capture, is never checked")
rep("while both IEEE 300-bus groups pass -- so the failure is a property of the action set rather "
    "than of the test system or of the test problem.",
    "while both IEEE 300-bus groups pass. The failure is therefore a property of the action set "
    "rather than of the test system or of the test problem.")
rep("the maximizing action is not unique and the step carries no ordering information -- this is the "
    "per-step form of the identifiability condition of Section 2.6",
    "the maximizing action is not unique and the step carries no ordering information. This is the "
    "per-step form of the identifiability condition of Section 2.6")
rep("With $S^{\\mathrm{my}}_t$ the chain generated by the one-step exact rule -- at each step "
    "reconnecting the admissible line of maximum $r$ -- the lookahead gap is",
    "With $S^{\\mathrm{my}}_t$ the chain generated by the one-step exact rule, which at each step "
    "reconnects the admissible line of maximum $r$, the lookahead gap is")
rep("even at depth 1 -- replanning, but with a single step of evidence -- it captures a substantial "
    "fraction.",
    "even at depth 1, that is, replanning with a single step of evidence, it captures more than half "
    "of it.")
rep("removing that mechanism accounts for the entire advantage that screening confers -- which is "
    "exactly the confound Proposition 1 was built to expose.",
    "removing that mechanism accounts for the entire advantage that screening confers. This is exactly "
    "the confound Proposition 1 was built to expose.")
rep("and that a phase diagram -- rather than a single-point comparison against a legacy configuration "
    "-- is the appropriate instrument for choosing it.",
    "and that a phase diagram, rather than a single-point comparison against a legacy configuration, "
    "is the appropriate instrument for choosing it.")
rep("The measured per-condition advantages -- 8.74, 5.27, 6.97, 4.38, 8.37, 4.93, 8.95, 2.51, 0.00, "
    "2.70, 0.73, 3.84 -- agree with",
    "The measured per-condition advantages of 8.74, 5.27, 6.97, 4.38, 8.37, 4.93, 8.95, 2.51, 0.00, "
    "2.70, 0.73 and 3.84 agree with")
rep("The third route, a service functional that is not exactly evaluable at decision time -- "
    "stochastic restoration outcomes, protection actions, cascading dynamics -- remains open",
    "The third route, a service functional that is not exactly evaluable at decision time (stochastic "
    "restoration outcomes, protection actions, cascading dynamics), remains open")
rep("- **R1** -- the utilisation-proportional rule with the floor share of the main protocol "
    "($\\phi = 0.002$);\n- **R2** -- the same rule with a tenfold larger floor ($\\phi = 0.05$);\n"
    "- **R3** -- uniform physical thermal ratings;\n- **R4** -- the utilisation-proportional rule "
    "with **no** floor.",
    "- **R1**: the utilisation-proportional rule with the floor share of the main protocol "
    "($\\phi = 0.002$);\n- **R2**: the same rule with a tenfold larger floor ($\\phi = 0.05$);\n"
    "- **R3**: uniform physical thermal ratings;\n- **R4**: the utilisation-proportional rule "
    "with **no** floor.")
rep("| IEEE 300 moderate 1.50 | 0.000 / 0.000 | 0/20 | -- | 0.000 / 0.000 | 0/20 | -- |",
    "| IEEE 300 moderate 1.50 | 0.000 / 0.000 | 0/20 | n/a | 0.000 / 0.000 | 0/20 | n/a |")
rep("| Committed plan, uncoupled | 0.3% | 5% | 15% | 21% | -- |",
    "| Committed plan, uncoupled | 0.3% | 5% | 15% | 21% | n/a |")
rep("| **Rolling, uncoupled** | **62%** | **99.4%** | **100%** | 100% | -- |",
    "| **Rolling, uncoupled** | **62%** | **99.4%** | **100%** | 100% | n/a |")

# ------------------------------------------------------- verified numeric fixes
rep("reaches 120.1 AUC units under a reconnection budget",
    "reaches 120.1 AUC@25 units under a reconnection budget")
rep("Third, the gap is a two-dimensional object. Its *value* is bounded by the gap itself; its "
    "*accessibility* is governed by a depth profile that we introduce. A committed plan needs five "
    "steps of foresight to realise the gap; a rolling depth-2 controller realises 99.4--99.8% of it, "
    "and depth 3 realises it exactly.",
    "Third, the gap is a two-dimensional object. Its magnitude bounds what any policy can gain; how "
    "cheaply that gain can be collected is a separate question, governed by a depth profile that we "
    "introduce. A committed plan needs five steps of foresight to collect the whole gap; a rolling "
    "depth-2 controller collects 99.4--99.8% of it, and depth 3 collects it exactly.")
rep("Yet learned rankers are dominated in all 240 paired comparisons",
    "However, learned rankers are dominated in all 240 paired comparisons")
rep("| IEEE 300 severe 1.15 | 1.489 / 8.601 | 10/20 | 6.5 | 2.762 / 50.841 | 4/20 | 4.0 |",
    "| IEEE 300 severe 1.15 | 1.489 / 8.601 | 10/20 | 6.5 | 2.762 / 50.840 | 4/20 | 4.0 |")
rep("The budget also restores the terminal term: with $B < m$ the terminal set is itself a decision, "
    "and the terminal-recovery gap between the one-step rule and the optimum reaches "
    "**27.2 percentage points** (70.65% versus 97.86%).",
    "The budget also restores the terminal term: with $B < m$ the terminal set is itself a decision, "
    "and the terminal-recovery gap between the one-step exact rule and the optimum averages "
    "**17.4 percentage points** over all conditions (80.2% versus 97.6%) and reaches "
    "**27.9 percentage points** in the most affected one (IEEE 118 severe at $\\kappa = 1.15$: "
    "69.3% versus 97.1%).")
rep("Measured against the offline optimum rather than against the gap, the rolling controller at "
    "depth 2 already attains 99.99% of the exact optimum in the budgeted setting and 100.00% without "
    "a budget, and it is exact at depth 3.",
    "Measured against the offline optimum rather than against the gap, the rolling controller at "
    "depth 2 already attains a mean of 99.99% of the exact optimum in the budgeted setting and "
    "99.998% without a budget, and it is exact at depth 3.")
rep("and it attains 100.0% of the offline optimum in eleven of the twelve conditions and 99.99% in "
    "the twelfth.",
    "and it attains the exact offline optimum in ten of the twelve conditions and no less than "
    "99.995% of it in the other two.")
rep("Those twelve advantages have a mean of 4.7 AUC@25 units and a maximum of 8.95, whereas the "
    "learned variants lose by 324.0 to 946.1 units.",
    "Those twelve advantages reach 8.95 and average 4.78 over the 240 paired comparisons, whereas "
    "the learned variants lose by 324.0 to 946.1 units.")
rep("The method is unchanged and the measured latency differs by a factor of **2.5**.",
    "The method is unchanged and the measured latency differs by a factor of **2.5--3.0** across "
    "the four condition groups.")
rep("the screened learned ranker is **51--60 times slower**, and the one-step exact rule is "
    "**290--1237 times slower** than the screened ranker.",
    "the screened learned ranker is **48--59 times slower**, and the one-step exact rule is "
    "**290--1236 times slower** than the screened ranker.")
rep("so a latency claim is a claim about a factor of 51--60 rather than about an absolute number.",
    "so a latency claim is a claim about a factor of 48--59 rather than about an absolute number.")
rep("The 2.5-fold difference above is entirely a boundary effect.",
    "The 2.5--3.0-fold difference above is a boundary effect and nothing else.")
rep("The same network is measured 2.5 times slower under one timing boundary than another, and the "
    "cheapest rule is 51--60 times faster than the learned one under either boundary.",
    "The same network is measured 2.5--3.0 times slower under one timing boundary than another, and "
    "the cheapest rule is 48--59 times faster than the learned one under either boundary.")
rep("The rolling depth-2 rule realizes 99.8% of the gap and 99.99% of the offline optimum,",
    "The rolling depth-2 rule realizes 99.8% of the gap and 99.999% of the offline optimum,")
rep("Sweeping the budget $B \\in \\{0,4,6,8\\}$ against the same twelve conditions (528 scenarios, one "
    "instance set shared across all budgets) gives the phase structure of the criterion.",
    "Sweeping the budget $B \\in \\{0,4,6,8\\}$ over the same twelve conditions gives the phase "
    "structure of the criterion: 132 instances are evaluated under each of the four budgets, 528 "
    "evaluations in total, on one instance set shared across all budgets.")
rep("computed at the nominal margin", "computed across the three capacity margins")

# ------------------------------------------------------------------- table 7
rep("""**Table 7.** Rolling depth-2 lookahead against every alternative. Aligned sample: 12 conditions $\\times$ 20 scenarios. $\\Delta$ = mean AUC@25 advantage of the rolling depth-2 rule; worst $p$ is the largest Wilcoxon $p$-value over the twelve conditions.

| Alternative | Wins | Ties | Losses | Mean $\\Delta$ | Worst $p$ |
|---|---|---|---|---|---|
| Learned ranker | 240 | 0 | **0** | +946.1 | $<10^{-4}$ |
| Risk-only rule | 240 | 0 | **0** | +783.5 | $<10^{-4}$ |
| Uniformly random | 240 | 0 | **0** | +750.4 | $<10^{-4}$ |
| True-objective ranker | 240 | 0 | **0** | +727.1 | $<10^{-4}$ |
| Learned ranker, screened | 240 | 0 | **0** | +419.4 | $<10^{-4}$ |
| True-objective ranker, screened | 240 | 0 | **0** | +324.0 | $<10^{-4}$ |
| Electrical-priority rule | 213 | 27 | **0** | +80.6 | 0.0015 |
| One-step exact rule | 35 | 205 | **0** | +4.78 | $2.5\\times10^{-7}$ |""",
    """**Table 7.** Rolling depth-2 lookahead against every alternative. Aligned sample: 12 conditions $\\times$ 20 scenarios, 240 paired comparisons per alternative. $\\Delta$ = mean AUC@25 advantage of the rolling depth-2 rule. Worst $p$ is the largest of the twelve per-condition Wilcoxon $p$-values; pooled $p$ is the Wilcoxon $p$-value over all 240 pairs.

| Alternative | Wins | Ties | Losses | Mean $\\Delta$ | Worst $p$ | Pooled $p$ |
|---|---|---|---|---|---|---|
| Learned ranker | 240 | 0 | **0** | +946.1 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| Risk-only rule | 240 | 0 | **0** | +783.5 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| Uniformly random | 240 | 0 | **0** | +750.4 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| True-objective ranker | 240 | 0 | **0** | +727.1 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| Learned ranker, screened | 240 | 0 | **0** | +419.4 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| True-objective ranker, screened | 240 | 0 | **0** | +324.0 | $1.9\\times10^{-6}$ | $4.0\\times10^{-41}$ |
| Electrical-priority rule | 213 | 27 | **0** | +80.6 | 0.0015 | $1.1\\times10^{-36}$ |
| One-step exact rule | 35 | 205 | **0** | +4.78 | **1.00** | $2.5\\times10^{-7}$ |

The last row requires a note. Against the one-step exact rule, 205 of the 240 pairs are ties, so the per-condition tests are underpowered and one condition is tied at every scenario; the pooled test remains decisive at $p = 2.5\\times10^{-7}$, and no pair is lost. The pooled column is close to degenerate for the six arm-level alternatives because no pair is tied there.""")
rep("Third, against the one-step exact rule the rolling rule wins 35 times, ties 205 times and never "
    "loses, for a mean advantage of +4.78 units.",
    "Third, against the one-step exact rule the rolling rule wins 35 times, ties 205 times and never "
    "loses, for a mean advantage of +4.78 units; with 205 of 240 pairs tied, the evidence for that "
    "row rests on the pooled test ($p = 2.5\\times10^{-7}$) rather than on the per-condition tests, "
    "which is why Table 7 reports both.")

# --------------------------------------------------------------------- header
rep("> **Manuscript revised for SEGAN (Sustainable Energy, Grids and Networks), 2026-09-13**\n"
    "> Elsevier `elsarticle`, numbered references, single-anonymized. Body target \u2248 9,000 words.\n"
    "> All numerical statements are traceable to `supp_results_2026-09-13/results/` (see Appendix D).",
    "> **Manuscript prepared for SEGAN (Sustainable Energy, Grids and Networks).**\n"
    "> Elsevier `elsarticle`, numbered references, single-anonymized. All numerical statements are\n"
    "> traceable to the released artifacts of Appendix D; `figures/MANIFEST.txt` records the input\n"
    "> file of every figure.")


def main() -> int:
    global s
    bad = 0
    for old, new in R:
        n = s.count(old)
        if n != 1:
            print(f"!! count={n}  {old[:78]!r}")
            bad += 1
            continue
        s = s.replace(old, new)
    if bad:
        print(f"\n{bad} replacement(s) did not match exactly; nothing written.")
        return 1
    P.write_text(s, encoding="utf-8")
    print(f"applied {len(R)} replacements; file grew {len(s)-len(orig):+d} chars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
